name: .NET Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [Release]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore Progetto/ConsoleApp1/ConsoleApp1.sln

    - name: Build solution
      run: dotnet build Progetto/ConsoleApp1/ConsoleApp1.sln --configuration ${{ matrix.configuration }} --no-restore

    - name: Run tests
      run: dotnet test Progetto/ConsoleApp1/ConsoleApp1.sln --configuration ${{ matrix.configuration }} --no-build

    # Upload the MSIX package: https://github.com/marketplace/actions/upload-a-build-artifact
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: MSIX Package
        path: ${{ env.Wap_Project_Directory }}\AppPackages
